### ISSUE TITLE
kernel 6.1

### ISSUE THREAD

**Issue by manchelsi** [sroeschus/uksm#1]
Do you plan to add kernel version 6.1?

**Comment by sroeschus** [comment]
6.1 and 6.2 are on the list.

With 6.1 I already started, however the mmap interface and the introduction of the maple tree in 6.1 make this more complicated. Its not a simple port. This will be similar to 5.19 and require additional work. The maple_tree allows to change the size of VMA to change without deleting the corresponding entries from the radix tree. This requires new changes to the uksm code. Currently I hit a BUG check that the size of the vma_slot and the vma is not the same, which is not unexpected. 

I don't need this for my work, so I'll get to it when I have time.

**Comment by sroeschus** [comment]
Just uploaded the patch for 6.1

**Comment by sroeschus** [comment]
.

**Comment by manchelsi** [comment]
Debian 12 install linux-source,
```
root@kernel-build:/usr/src/linux-source-6.1# patch -p1 < uksm-v6.1.patch 
patching file Documentation/vm/uksm.txt
patching file fs/exec.c
patching file fs/proc/meminfo.c
patching file include/linux/ksm.h
patching file include/linux/mm_types.h
Hunk #1 succeeded at 520 (offset 14 lines).
patching file include/linux/mmzone.h
patching file include/linux/pgtable.h
patching file include/linux/sradix-tree.h
patching file include/linux/uksm.h
patching file kernel/fork.c
Hunk #1 succeeded at 487 (offset 6 lines).
Hunk #2 succeeded at 699 (offset 11 lines).
patching file lib/Makefile
patching file lib/sradix-tree.c
patching file mm/Kconfig
Hunk #1 succeeded at 682 (offset 24 lines).
patching file mm/Makefile
patching file mm/ksm.c
patching file mm/memory.c
Hunk #3 succeeded at 994 (offset 6 lines).
Hunk #4 succeeded at 1462 (offset 6 lines).
Hunk #5 FAILED at 2887.
Hunk #6 succeeded at 3175 (offset 34 lines).
Hunk #7 succeeded at 3223 (offset 36 lines).
1 out of 7 hunks FAILED -- saving rejects to file mm/memory.c.rej
patching file mm/mmap.c
Hunk #2 succeeded at 141 (offset -1 lines).
Hunk #3 succeeded at 564 (offset 2 lines).
Hunk #4 succeeded at 601 (offset 2 lines).
Hunk #5 succeeded at 641 with fuzz 2 (offset 6 lines).
Hunk #6 succeeded at 809 (offset 13 lines).
Hunk #7 succeeded at 874 (offset 13 lines).
Hunk #8 succeeded at 1338 with fuzz 1 (offset 13 lines).
Hunk #9 succeeded at 2401 (offset 144 lines).
Hunk #10 succeeded at 2842 (offset 127 lines).
Hunk #11 succeeded at 2900 with fuzz 2 (offset 120 lines).
Hunk #12 succeeded at 3102 (offset 149 lines).
Hunk #13 succeeded at 3135 (offset 149 lines).
Hunk #14 succeeded at 3165 (offset 149 lines).
Hunk #15 succeeded at 3295 (offset 150 lines).
Hunk #16 succeeded at 3412 (offset 150 lines).
Hunk #17 succeeded at 3588 (offset 149 lines).
patching file mm/uksm.c
patching file mm/vmstat.c
```
```
root@kernel-build:/usr/src/linux-source-6.1# cat mm/memory.c.rej
--- mm/memory.c
+++ mm/memory.c
@@ -2887,6 +2914,7 @@ static inline bool __wp_page_copy_user(struct page *dst, struct page *src,
 
        if (likely(src)) {
                copy_user_highpage(dst, src, addr, vma);
+               uksm_cow_page(vma, src);
                return true;
        }
 

```

**Comment by manchelsi** [comment]
Maybe it's because the function you need is on a different line?
```
2891         if (likely(src)) {
2892                 if (copy_mc_user_highpage(dst, src, addr, vma)) {
2893                         memory_failure_queue(page_to_pfn(src), 0);
2894                         return -EHWPOISON;
2895                 }
2896                 return 0;
2897         }
2898                  
```

**Comment by manchelsi** [comment]
The sources on kernel.org also have discrepancies with the patch

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/mm/memory.c?h=v6.1.121#n2922

**Comment by sroeschus** [comment]
The problem is that you didn't apply this on 6.1.0, but instead on 6.1.121. This means that 121 additional patchsets have been applied on top of it. I'm actually surprised you got so little conflicts. For the conflict you mentioned I think it should be:

**Comment by sroeschus** [comment]
if (likely(src)) {
                     if (copy_mc_user_highpage(dst, src, addr, vma)) {
                             memory_failure_queue(page_to_pfn(src), 0);
                             return -EHWPOISON;
                     }
                     uksm_cow_page(vma, src);
                     return 0;
             }

**Comment by manchelsi** [comment]
Yesterday I checked 6.11 with your patches and xanmod patches, it works great. Thank you.

**Comment by sroeschus** [comment]
Thanks for the feedback, its appreciated.
